# Generated by Django 3.2.15 on 2022-09-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=500)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=500)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('resident', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('job_des', models.TextField()),
                ('language', models.CharField(choices=[('English', 'English'), ('Amharic', 'Amharic')], max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('Female', 'Female'), ('other', 'other')], max_length=200)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.education')),
                ('expirience', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.exprience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
