# Generated by Django 3.2.15 on 2022-09-10 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='exprience',
            name='resume',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.education'),
        ),
        migrations.AddField(
            model_name='resume',
            name='expirience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.exprience'),
        ),
    ]
