# Generated by Django 3.2.15 on 2022-09-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220907_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
