# Generated by Django 3.2.15 on 2022-09-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220910_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exprience',
            name='user',
        ),
    ]
